# -*-  coding: ascii -*-  # # # # # # # # # # # # # # # # # # # # # # # # # # #

__package__ = "pypes.codecs_.mrs";
__all__ = [ "MRSInterpreter" ];

from pypes.utils.mc import subject;



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

class MRSInterpreter( metaclass=subject ):
  
  SEMI_PREDICATES = {
      'ABSTR_DEG': {'ARG0': ('x', None)},
      'ADDRESSEE': {'ARG0': ('i', None),
                    'ARG1': ('u', None),
                    'ARG2': ('u', None)},
      'ALL_TOO': {'ARG0': ('e', None),
                  'ARG1': ('u', None),
                  'ARG2': ('u', None)},
      'APPOS': {'ARG0': ('e', None), 'ARG1': ('x', {'NUM': 'pl'})},
      'APPROX_GRAD': {'ARG0': ('i', None), 'ARG1': ('i', None)},
      'ARGUMENT': {'ARG0': ('e', None),
                   'ARG1': ('e', None),
                   'ARG2': ('x', None)},
      'CARD': {'ARG0': ('e', None),
               'ARG1': ('i', {'IND': '+', 'NUM': 'pl'})},
      'CARD_OF': {'ARG0': ('i', {'IND': '+', 'NUM': 'pl'})},
      'COMP': {'ARG0': ('e', None), 'ARG1': ('e', None)},
      'COMPOUND': {'ARG0': ('i', None), 'ARG1': ('i', {'IND': '+'})},
      'COMPOUND_NAME': {'ARG0': ('i', None),
                        'ARG1': ('u', None),
                        'ARG2': ('x', {'IND': '+', 'NUM': 'pl'})},
      'COMP_ENOUGH': {'ARG0': ('e', None),
                      'ARG1': ('u', None),
                      'ARG2': ('h', None)},
      'COMP_EQUAL': {'ARG0': ('e', None),
                     'ARG1': ('u', None),
                     'ARG2': ('u', None)},
      'COMP_LESS': {'ARG0': ('e', None),
                    'ARG1': ('u', None),
                    'ARG2': ('u', None)},
      'COMP_SO': {'ARG0': ('e', None),
                  'ARG1': ('u', None),
                  'ARG2': ('u', None)},
      'COMP_TOO': {'ARG0': ('e', None),
                   'ARG1': ('u', None),
                   'ARG2': ('u', None)},
      'DEFEQUAL_V': {'ARG0': ('e', None),
                     'ARG1': ('e', None),
                     'ARG2': ('u', None)},
      'DEF_EXPLICIT_Q': {'ARG0': ('x', {'NUM': 'sg'})},
      'DEF_IMPLICIT_Q': {'ARG0': ('x', {'NUM': 'sg'})},
      'DEF_Q': {'ARG0': ('x', None),
                'BODY': ('h', None),
                'RSTR': ('h', None)},
      'DEF_UDEF_A_Q': {'ARG0': ('x', None),
                       'BODY': ('h', None),
                       'RSTR': ('h', None)},
      'DEF_UDEF_SOME_A_Q': {'ARG0': ('x', None),
                            'BODY': ('h', None),
                            'RSTR': ('h', None)},
      'DELETE_X_1': {'ARG0': ('e', None), 'ARG1': ('h', None)},
      'DISCOURSE': {'ARG0': ('i', None),
                    'L-HNDL': ('h', None),
                    'L-INDEX': ('i', None),
                    'R-HNDL': ('h', None),
                    'R-INDEX': ('i', None)},
      'DOFM': {'ARG0': ('i', {'GEND': 'n', 'IND': '-', 'NUM': 'sg'})},
      'DOFW': {'ARG0': ('i', {'IND': '+'})},
      'ELLIPSIS': {'ARG0': ('e', None), 'ARG1': ('u', None)},
      'ELLIPSIS_EXPL': {'ARG0': ('e', None), 'ARG1': ('u', None)},
      'ELLIPSIS_REF': {'ARG0': ('e', None), 'ARG1': ('u', None)},
      'ELLIPTICAL_N': {'ARG0': ('x', None)},
      'EVERY_Q': {'ARG0': ('x', {'NUM': 'sg'})},
      'EXCL': {'ARG0': ('i', None)},
      'EXPECTED_EVENT_V': {'ARG0': ('e', None), 'ARG1': ('h', None)},
      'FOCUS_D': {'ARG0': ('e', None),
                  'ARG1': ('e', None),
                  'ARG2': ('u', None)},
      'FRACTION': {'ARG0': ('i', None), 'ARG1': ('i', None)},
      'FREE_RELATIVE_EVER_Q': {'ARG0': ('x', None),
                               'BODY': ('h', None),
                               'RSTR': ('h', None)},
      'FREE_RELATIVE_Q': {'ARG0': ('x', None),
                          'BODY': ('h', None),
                          'RSTR': ('h', None)},
      'FW_SEQ': {'ARG0': ('i', None),
                 'L-INDEX': ('i', None),
                 'R-INDEX': ('i', None)},
      'GENERIC_ENTITY': {'ARG0': ('x', {'GEND': 'n', 'NUM': 'sg'})},
      'GENERIC_NOM': {'ARG0': ('i', {'IND': '+'})},
      'GENERIC_VERB': {'ARG0': ('e', None)},
      'GEN_NUMVAL': {'ARG0': ('i', {'IND': '+', 'NUM': 'pl'})},
      'GREET': {'ARG0': ('i', None)},
      'GUESS': {'ARG0': ('i', None)},
      'HOLIDAY': {'ARG0': ('i', {'IND': '+', 'NUM': 'sg'})},
      'HOUR_PREP': {'ARG0': ('i', None), 'ARG1': ('x', {'NUM': 'sg'})},
      'ID': {'ARG0': ('e', None), 'ARG1': ('x', {'NUM': 'sg'})},
      'IDIOM_Q': {'ARG0': ('x', None),
                  'BODY': ('h', None),
                  'RSTR': ('h', None)},
      'IDIOM_Q_I': {'ARG0': ('x', None),
                    'BODY': ('h', None),
                    'RSTR': ('h', None)},
      'IMPLICIT_CONJ': {'ARG0': ('i', None),
                        'L-INDEX': ('i', None),
                        'R-INDEX': ('x', None)},
      'IMPLICIT_Q': {'ARG0': ('x', None),
                     'BODY': ('h', None),
                     'RSTR': ('h', None)},
      'INTERVAL': {'ARG0': ('x', None), 'u': (']', None)},
      'INTERVAL_P_END': {'ARG0': ('i', None),
                         'ARG1': ('x', None),
                         'ARG2': ('u', None)},
      'INTERVAL_P_START': {'ARG0': ('e', None),
                           'ARG1': ('x', None),
                           'ARG2': ('u', None)},
      'LITTLE_FEW_A': {'ARG0': ('e', None), 'ARG1': ('i', None)},
      'LOC_NONSP': {'ARG0': ('e', None),
                    'ARG1': ('u', None),
                    'ARG2': ('x', {'NUM': 'sg'})},
      'LOC_SP': {'ARG0': ('i', None),
                 'ARG1': ('u', None),
                 'ARG2': ('u', None)},
      'MANNER': {'ARG0': ('x', {'NUM': 'sg'})},
      'MEASURE': {'ARG0': ('e', None),
                  'ARG1': ('u', None),
                  'ARG2': ('u', None)},
      'MINUTE': {'ARG0': ('i', {'NUM': 'sg'})},
      'MOFY': {'ARG0': ('i', {'IND': '+'})},
      'MUCH_MANY_A': {'ARG0': ('e', None), 'ARG1': ('i', None)},
      'NAMED': {'ARG0': ('x', {'GEND': 'f', 'IND': '+'})},
      'NAMED_N': {'ARG0': ('i', {'IND': '+'})},
      'NAMED_UNK': {'ARG0': ('x', {'IND': '+'})},
      'NEG': {'ARG0': ('i', None), 'h': (']', None)},
      'NE_X': {'ARG0': ('e', None),
               'ARG1': ('h', None),
               'ARG2': ('h', None)},
      'NOMINALIZATION': {'ARG0': ('x', {'NUM': 'sg'})},
      'NONTEMP_LOC_SP': {'ARG0': ('i', None),
                         'ARG1': ('u', None),
                         'ARG2': ('u', None)},
      'NONTEMP_SP_OR_NONSP': {'ARG0': ('i', None),
                              'ARG1': ('u', None),
                              'ARG2': ('u', None)},
      'NOT_X_DEG': {'ARG0': ('e', None), 'ARG1': ('u', None)},
      'NUMBERED_HOUR': {'ARG0': ('x', {'NUM': 'sg'})},
      'NUMBER_Q': {'ARG0': ('x', None),
                   'BODY': ('h', None),
                   'RSTR': ('h', None)},
      'NUM_SEQ': {'ARG0': ('i', {'NUM': 'sg'})},
      'OF_P': {'ARG0': ('i', None),
               'ARG1': ('u', None),
               'ARG2': ('x', None)},
      'ORD': {'ARG0': ('i', None), 'ARG1': ('i', None)},
      'PARENTHETICAL': {'ARG0': ('i', None),
                        'ARG1': ('i', None),
                        'ARG2': ('h', None)},
      'PARG_D': {'ARG0': ('e', None),
                 'ARG1': ('e', None),
                 'ARG2': ('u', None)},
      'PART_OF': {'ARG0': ('x', {'NUM': 'pl'})},
      'PERSON': {'ARG0': ('x', None)},
      'PLACE_N': {'ARG0': ('x', None)},
      'PLUS': {'ARG0': ('i', None), 'ARG1': ('i', {'NUM': 'pl'})},
      'POLITE': {'ARG0': ('i', None), 'ARG1': ('u', None)},
      'POSS': {'ARG0': ('e', None),
               'ARG1': ('x', None),
               'ARG2': ('x', {'GEND': 'm', 'NUM': 'sg'})},
      'PREDNOM_STATE': {'ARG0': ('e', None), 'ARG1': ('x', None)},
      'PRON': {'ARG0': ('x', {'GEND': 'm-or-f', 'NUM': 'sg'})},
      'PRONOUN_Q': {'ARG0': ('x', {'GEND': 'm', 'NUM': 'sg'})},
      'PROPERTY': {'ARG0': ('x', None)},
      'PROPER_Q': {'ARG0': ('x', None),
                   'BODY': ('h', None),
                   'RSTR': ('h', None)},
      'PRPSTN_TO_PROP': {'ARG0': ('e', None),
                         'ARG1': ('h', None),
                         'ARG2': ('x', None)},
      'QUANT': {'ARG0': ('x', None),
                'BODY': ('h', None),
                'RSTR': ('h', None)},
      'REASON': {'ARG0': ('x', None)},
      'RECIP_PRO': {'ARG0': ('x', None)},
      'REFL_MOD': {'ARG0': ('e', None),
                   'ARG1': ('e', None),
                   'ARG2': ('x', {'GEND': 'm-or-f', 'NUM': 'sg'})},
      'SEASON': {'ARG0': ('i', {'IND': '+'})},
      'SOME_Q': {'ARG0': ('x', None),
                 'BODY': ('h', None),
                 'RSTR': ('h', None)},
      'SUBORD': {'ARG0': ('e', None),
                 'ARG1': ('h', None),
                 'ARG2': ('h', None)},
      'SUPERL': {'e': (']', None), 'u': (']', None)},
      'TEMP': {'ARG0': ('x', None)},
      'TEMP_LOC_SP': {'ARG0': ('i', None),
                      'ARG1': ('u', None),
                      'ARG2': ('u', None)},
      'TEMP_LOC_X': {'ARG0': ('e', None),
                     'ARG1': ('u', None),
                     'ARG2': ('x', {'NUM': 'sg'})},
      'TEMP_SP_OR_NONSP': {'ARG0': ('i', None),
                           'ARG1': ('u', None),
                           'ARG2': ('u', None)},
      'TERM': {'ARG0': ('e', None), 'ARG1': ('i', {'IND': '+'})},
      'THING': {'ARG0': ('x', None)},
      'TIMES': {'ARG0': ('i', None),
                'ARG1': ('u', None),
                'ARG2': ('h', None),
                'ARG3': ('h', None)},
      'TIME_N': {'ARG0': ('x', None)},
      'UDEF_Q': {'ARG0': ('x', {'NUM': 'pl'})},
      'UNKNOWN': {'ARG': ('i', {'NUM': 'pl'}), 'ARG0': ('e', None)},
      'UNSPEC_ADJ': {'ARG0': ('i', None), 'ARG1': ('x', None)},
      'UNSPEC_LOC': {'ARG0': ('i', None),
                     'ARG1': ('u', None),
                     'ARG2': ('u', None)},
      'UNSPEC_MANNER': {'ARG0': ('e', None),
                        'ARG1': ('u', None),
                        'ARG2': ('x', {'NUM': 'sg'})},
      'V_EVENT': {'ARG0': ('e', None)},
      'WHICH_Q': {'ARG0': ('x', {'NUM': 'sg'})},
      'WITH_P': {'ARG0': ('e', None),
                 'ARG1': ('u', None),
                 'ARG2': ('u', None)},
      'YOFC': {'ARG0': ('i', {'IND': '+', 'NUM': 'sg'})}
    };



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
#        PyPES: the python platform for experimentation with semantics        #
#                                                                             #
#                  (c) Copyright 2009 by Richard Bergmair                     #
#       -----------------------------------------------------------------     #
#       See LICENSE.txt for terms and conditions on use and reproduction.     #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
