# -*-  coding: ascii -*-

__package__ = "pypes.proto.lex";
__all__ = [ "Operator" ];

from pypes.utils.mc import kls;
from pypes.proto.lex import basic;

class Operator( basic.Operator, metaclass=kls ):

  ABSTR_DEG = 'ABSTR_DEG';
  ADDRESSEE = 'ADDRESSEE';
  ALL_TOO = 'ALL_TOO';
  APPOS = 'APPOS';
  APPROX_GRAD = 'APPROX_GRAD';
  ARGUMENT = 'ARGUMENT';
  BASIC_CARD = 'BASIC_CARD';
  BASIC_NUMBERED_HOUR = 'BASIC_NUMBERED_HOUR';
  BASIC_YOFC = 'BASIC_YOFC';
  CARD = 'CARD';
  CARD_OF = 'CARD_OF';
  COMP = 'COMP';
  COMPOUND = 'COMPOUND';
  COMPOUND_NAME = 'COMPOUND_NAME';
  COMP_ENOUGH = 'COMP_ENOUGH';
  COMP_EQUAL = 'COMP_EQUAL';
  COMP_LESS = 'COMP_LESS';
  COMP_SO = 'COMP_SO';
  COMP_TOO = 'COMP_TOO';
  DAY = 'DAY';
  DEFEQUAL_V = 'DEFEQUAL_V';
  DEF_EXPLICIT_Q = 'DEF_EXPLICIT_Q';
  DEF_IMPLICIT_Q = 'DEF_IMPLICIT_Q';
  DEF_Q = 'DEF_Q';
  DEF_UDEF_A_Q = 'DEF_UDEF_A_Q';
  DEF_UDEF_SOME_A_Q = 'DEF_UDEF_SOME_A_Q';
  DELETE_X_1 = 'DELETE_X_1';
  DISCOURSE = 'DISCOURSE';
  DOFM = 'DOFM';
  DOFW = 'DOFW';
  ELLIPSIS = 'ELLIPSIS';
  ELLIPSIS_EXPL = 'ELLIPSIS_EXPL';
  ELLIPSIS_REF = 'ELLIPSIS_REF';
  ELLIPTICAL_N = 'ELLIPTICAL_N';
  EVERY_Q = 'EVERY_Q';
  EXCL = 'EXCL';
  EXPECTED_EVENT_V = 'EXPECTED_EVENT_V';
  FOCUS_D = 'FOCUS_D';
  FRACTION = 'FRACTION';
  FREE_RELATIVE_EVER_Q = 'FREE_RELATIVE_EVER_Q';
  FREE_RELATIVE_Q = 'FREE_RELATIVE_Q';
  FW_SEQ = 'FW_SEQ';
  GENERIC_ENTITY = 'GENERIC_ENTITY';
  GENERIC_NOM = 'GENERIC_NOM';
  GENERIC_VERB = 'GENERIC_VERB';
  GEN_NUMVAL = 'GEN_NUMVAL';
  GREET = 'GREET';
  GUESS = 'GUESS';
  HOLIDAY = 'HOLIDAY';
  HOUR_PREP = 'HOUR_PREP';
  ID = 'ID';
  IDIOM_Q = 'IDIOM_Q';
  IDIOM_Q_I = 'IDIOM_Q_I';
  IMPLICIT_CONJ = 'IMPLICIT_CONJ';
  IMPLICIT_Q = 'IMPLICIT_Q';
  INTERVAL = 'INTERVAL';
  INTERVAL_P_END = 'INTERVAL_P_END';
  INTERVAL_P_START = 'INTERVAL_P_START';
  LITTLE_FEW_A = 'LITTLE_FEW_A';
  LOC_NONSP = 'LOC_NONSP';
  LOC_SP = 'LOC_SP';
  MANNER = 'MANNER';
  MEASURE = 'MEASURE';
  MEAS_NOM = 'MEAS_NOM';
  MINUTE = 'MINUTE';
  MOFY = 'MOFY';
  MUCH_MANY_A = 'MUCH_MANY_A';
  NAMED = 'NAMED';
  NAMED_N = 'NAMED_N';
  NAMED_UNK = 'NAMED_UNK';
  NEG = 'NEG';
  NE_X = 'NE_X';
  NOMINALIZATION = 'NOMINALIZATION';
  NONTEMP_LOC_SP = 'NONTEMP_LOC_SP';
  NONTEMP_SP_OR_NONSP = 'NONTEMP_SP_OR_NONSP';
  NOT_X_DEG = 'NOT_X_DEG';
  NUMBERED_HOUR = 'NUMBERED_HOUR';
  NUMBER_Q = 'NUMBER_Q';
  NUM_SEQ = 'NUM_SEQ';
  OF_P = 'OF_P';
  ORD = 'ORD';
  PARENTHETICAL = 'PARENTHETICAL';
  PARG_D = 'PARG_D';
  PART_OF = 'PART_OF';
  PERSON = 'PERSON';
  PLACE_N = 'PLACE_N';
  PLUS = 'PLUS';
  POLITE = 'POLITE';
  POSS = 'POSS';
  PREDNOM_STATE = 'PREDNOM_STATE';
  PRON = 'PRON';
  PRONOUN_Q = 'PRONOUN_Q';
  PROPERTY = 'PROPERTY';
  PROPER_Q = 'PROPER_Q';
  PRPSTN_TO_PROP = 'PRPSTN_TO_PROP';
  QUANT = 'QUANT';
  REASON = 'REASON';
  RECIP_PRO = 'RECIP_PRO';
  REFL_MOD = 'REFL_MOD';
  SEASON = 'SEASON';
  SOME_Q = 'SOME_Q';
  SUBORD = 'SUBORD';
  SUPERL = 'SUPERL';
  TEMP = 'TEMP';
  TEMP_LOC_SP = 'TEMP_LOC_SP';
  TEMP_LOC_X = 'TEMP_LOC_X';
  TEMP_SP_OR_NONSP = 'TEMP_SP_OR_NONSP';
  TERM = 'TERM';
  THING = 'THING';
  TIMES = 'TIMES';
  TIME_N = 'TIME_N';
  UDEF_Q = 'UDEF_Q';
  UNKNOWN = 'UNKNOWN';
  UNSPEC_ADJ = 'UNSPEC_ADJ';
  UNSPEC_LOC = 'UNSPEC_LOC';
  UNSPEC_MANNER = 'UNSPEC_MANNER';
  V_EVENT = 'V_EVENT';
  WHICH_Q = 'WHICH_Q';
  WITH_P = 'WITH_P';
  YOFC = 'YOFC';

  OPs = {};
  OPs.update( basic.Operator.OPs );
  OPs.update( {
    ABSTR_DEG: ABSTR_DEG,
    ADDRESSEE: ADDRESSEE,
    ALL_TOO: ALL_TOO,
    APPOS: APPOS,
    APPROX_GRAD: APPROX_GRAD,
    ARGUMENT: ARGUMENT,
    BASIC_CARD: BASIC_CARD,
    BASIC_NUMBERED_HOUR: BASIC_NUMBERED_HOUR,
    BASIC_YOFC: BASIC_YOFC,
    CARD: CARD,
    CARD_OF: CARD_OF,
    COMP: COMP,
    COMPOUND: COMPOUND,
    COMPOUND_NAME: COMPOUND_NAME,
    COMP_ENOUGH: COMP_ENOUGH,
    COMP_EQUAL: COMP_EQUAL,
    COMP_LESS: COMP_LESS,
    COMP_SO: COMP_SO,
    COMP_TOO: COMP_TOO,
    DAY: DAY,
    DEFEQUAL_V: DEFEQUAL_V,
    DEF_EXPLICIT_Q: DEF_EXPLICIT_Q,
    DEF_IMPLICIT_Q: DEF_IMPLICIT_Q,
    DEF_Q: DEF_Q,
    DEF_UDEF_A_Q: DEF_UDEF_A_Q,
    DEF_UDEF_SOME_A_Q: DEF_UDEF_SOME_A_Q,
    DELETE_X_1: DELETE_X_1,
    DISCOURSE: DISCOURSE,
    DOFM: DOFM,
    DOFW: DOFW,
    ELLIPSIS: ELLIPSIS,
    ELLIPSIS_EXPL: ELLIPSIS_EXPL,
    ELLIPSIS_REF: ELLIPSIS_REF,
    ELLIPTICAL_N: ELLIPTICAL_N,
    EVERY_Q: EVERY_Q,
    EXCL: EXCL,
    EXPECTED_EVENT_V: EXPECTED_EVENT_V,
    FOCUS_D: FOCUS_D,
    FRACTION: FRACTION,
    FREE_RELATIVE_EVER_Q: FREE_RELATIVE_EVER_Q,
    FREE_RELATIVE_Q: FREE_RELATIVE_Q,
    FW_SEQ: FW_SEQ,
    GENERIC_ENTITY: GENERIC_ENTITY,
    GENERIC_NOM: GENERIC_NOM,
    GENERIC_VERB: GENERIC_VERB,
    GEN_NUMVAL: GEN_NUMVAL,
    GREET: GREET,
    GUESS: GUESS,
    HOLIDAY: HOLIDAY,
    HOUR_PREP: HOUR_PREP,
    ID: ID,
    IDIOM_Q: IDIOM_Q,
    IDIOM_Q_I: IDIOM_Q_I,
    IMPLICIT_CONJ: IMPLICIT_CONJ,
    IMPLICIT_Q: IMPLICIT_Q,
    INTERVAL: INTERVAL,
    INTERVAL_P_END: INTERVAL_P_END,
    INTERVAL_P_START: INTERVAL_P_START,
    LITTLE_FEW_A: LITTLE_FEW_A,
    LOC_NONSP: LOC_NONSP,
    LOC_SP: LOC_SP,
    MANNER: MANNER,
    MEASURE: MEASURE,
    MEAS_NOM: MEAS_NOM,
    MINUTE: MINUTE,
    MOFY: MOFY,
    MUCH_MANY_A: MUCH_MANY_A,
    NAMED: NAMED,
    NAMED_N: NAMED_N,
    NAMED_UNK: NAMED_UNK,
    NEG: NEG,
    NE_X: NE_X,
    NOMINALIZATION: NOMINALIZATION,
    NONTEMP_LOC_SP: NONTEMP_LOC_SP,
    NONTEMP_SP_OR_NONSP: NONTEMP_SP_OR_NONSP,
    NOT_X_DEG: NOT_X_DEG,
    NUMBERED_HOUR: NUMBERED_HOUR,
    NUMBER_Q: NUMBER_Q,
    NUM_SEQ: NUM_SEQ,
    OF_P: OF_P,
    ORD: ORD,
    PARENTHETICAL: PARENTHETICAL,
    PARG_D: PARG_D,
    PART_OF: PART_OF,
    PERSON: PERSON,
    PLACE_N: PLACE_N,
    PLUS: PLUS,
    POLITE: POLITE,
    POSS: POSS,
    PREDNOM_STATE: PREDNOM_STATE,
    PRON: PRON,
    PRONOUN_Q: PRONOUN_Q,
    PROPERTY: PROPERTY,
    PROPER_Q: PROPER_Q,
    PRPSTN_TO_PROP: PRPSTN_TO_PROP,
    QUANT: QUANT,
    REASON: REASON,
    RECIP_PRO: RECIP_PRO,
    REFL_MOD: REFL_MOD,
    SEASON: SEASON,
    SOME_Q: SOME_Q,
    SUBORD: SUBORD,
    SUPERL: SUPERL,
    TEMP: TEMP,
    TEMP_LOC_SP: TEMP_LOC_SP,
    TEMP_LOC_X: TEMP_LOC_X,
    TEMP_SP_OR_NONSP: TEMP_SP_OR_NONSP,
    TERM: TERM,
    THING: THING,
    TIMES: TIMES,
    TIME_N: TIME_N,
    UDEF_Q: UDEF_Q,
    UNKNOWN: UNKNOWN,
    UNSPEC_ADJ: UNSPEC_ADJ,
    UNSPEC_LOC: UNSPEC_LOC,
    UNSPEC_MANNER: UNSPEC_MANNER,
    V_EVENT: V_EVENT,
    WHICH_Q: WHICH_Q,
    WITH_P: WITH_P,
    YOFC: YOFC} );

  OP_Qs = basic.Operator.OP_Qs | {
    DEF_EXPLICIT_Q,
    DEF_IMPLICIT_Q,
    DEF_Q,
    DEF_UDEF_A_Q,
    DEF_UDEF_SOME_A_Q,
    EVERY_Q,
    FREE_RELATIVE_EVER_Q,
    FREE_RELATIVE_Q,
    IDIOM_Q,
    IDIOM_Q_I,
    IMPLICIT_Q,
    NUMBER_Q,
    PRONOUN_Q,
    PROPER_Q,
    QUANT,
    SOME_Q,
    UDEF_Q,
    WHICH_Q};

  OP_Cs = basic.Operator.OP_Cs | {
    ADDRESSEE,
    ALL_TOO,
    BASIC_NUMBERED_HOUR,
    COMP,
    COMP_ENOUGH,
    COMP_EQUAL,
    COMP_LESS,
    COMP_SO,
    COMP_TOO,
    DISCOURSE,
    IMPLICIT_CONJ,
    LOC_NONSP,
    LOC_SP,
    MEASURE,
    NE_X,
    NONTEMP_LOC_SP,
    NONTEMP_SP_OR_NONSP,
    NUMBERED_HOUR,
    PLUS,
    POSS,
    SUBORD,
    TEMP_LOC_SP,
    TEMP_LOC_X,
    TEMP_SP_OR_NONSP,
    TIMES,
    UNSPEC_LOC,
    WITH_P};

  OP_Ms = basic.Operator.OP_Ms | {
    ADDRESSEE,
    ALL_TOO,
    APPOS,
    BASIC_NUMBERED_HOUR,
    BASIC_YOFC,
    COMP,
    COMPOUND,
    COMPOUND_NAME,
    COMP_ENOUGH,
    COMP_EQUAL,
    COMP_LESS,
    COMP_SO,
    COMP_TOO,
    DEFEQUAL_V,
    DELETE_X_1,
    ELLIPSIS,
    ELLIPSIS_EXPL,
    ELLIPSIS_REF,
    EXPECTED_EVENT_V,
    FOCUS_D,
    ID,
    INTERVAL,
    INTERVAL_P_END,
    INTERVAL_P_START,
    LITTLE_FEW_A,
    LOC_NONSP,
    LOC_SP,
    MEASURE,
    MUCH_MANY_A,
    NEG,
    NE_X,
    NOMINALIZATION,
    NONTEMP_LOC_SP,
    NONTEMP_SP_OR_NONSP,
    NOT_X_DEG,
    NUMBERED_HOUR,
    OF_P,
    PARENTHETICAL,
    PARG_D,
    PLUS,
    POLITE,
    POSS,
    PRPSTN_TO_PROP,
    SUBORD,
    SUPERL,
    TEMP_LOC_SP,
    TEMP_LOC_X,
    TEMP_SP_OR_NONSP,
    TERM,
    TIMES,
    UNKNOWN,
    UNSPEC_LOC,
    UNSPEC_MANNER,
    WITH_P,
    YOFC};

  OP_Ps = basic.Operator.OP_Ps | {
    ABSTR_DEG,
    ADDRESSEE,
    ALL_TOO,
    APPOS,
    APPROX_GRAD,
    ARGUMENT,
    BASIC_CARD,
    BASIC_NUMBERED_HOUR,
    BASIC_YOFC,
    CARD,
    CARD_OF,
    COMP,
    COMPOUND,
    COMPOUND_NAME,
    COMP_EQUAL,
    COMP_LESS,
    COMP_SO,
    COMP_TOO,
    DAY,
    DEFEQUAL_V,
    DOFM,
    DOFW,
    ELLIPSIS,
    ELLIPSIS_EXPL,
    ELLIPSIS_REF,
    ELLIPTICAL_N,
    EXCL,
    FOCUS_D,
    FRACTION,
    FW_SEQ,
    GENERIC_ENTITY,
    GENERIC_NOM,
    GENERIC_VERB,
    GEN_NUMVAL,
    GREET,
    GUESS,
    HOLIDAY,
    HOUR_PREP,
    ID,
    IMPLICIT_CONJ,
    INTERVAL,
    INTERVAL_P_END,
    INTERVAL_P_START,
    LITTLE_FEW_A,
    LOC_NONSP,
    LOC_SP,
    MANNER,
    MEASURE,
    MEAS_NOM,
    MINUTE,
    MOFY,
    MUCH_MANY_A,
    NAMED,
    NAMED_N,
    NAMED_UNK,
    NONTEMP_LOC_SP,
    NONTEMP_SP_OR_NONSP,
    NOT_X_DEG,
    NUMBERED_HOUR,
    NUM_SEQ,
    OF_P,
    ORD,
    PARENTHETICAL,
    PARG_D,
    PART_OF,
    PERSON,
    PLACE_N,
    POLITE,
    POSS,
    PREDNOM_STATE,
    PRON,
    PROPERTY,
    REASON,
    RECIP_PRO,
    REFL_MOD,
    SEASON,
    SUPERL,
    TEMP,
    TEMP_LOC_SP,
    TEMP_LOC_X,
    TEMP_SP_OR_NONSP,
    TERM,
    THING,
    TIME_N,
    UNKNOWN,
    UNSPEC_ADJ,
    UNSPEC_LOC,
    UNSPEC_MANNER,
    V_EVENT,
    WITH_P,
    YOFC};


class Word( basic.Word, metaclass=kls ):

  WRD_Qs = basic.Word.WRD_Qs + [
    (['a'], 'q', 'on'),
    (['a', 'bit'], 'q', 'on'),
    (['a', 'little'], 'q', 'on'),
    (['all'], 'q', 'on'),
    (['another'], 'q', 'on'),
    (['any'], 'q', 'on'),
    (['any', 'more'], 'q', 'on'),
    (['both'], 'q', 'on'),
    (['each'], 'q', 'on'),
    (['either'], 'q', 'on'),
    (['enough'], 'q', 'on'),
    (['every'], 'q', 'on'),
    (['half'], 'q', 'on'),
    (['less'], 'q', 'on'),
    (['many', 'a'], 'q', 'on'),
    (['most'], 'q', 'on'),
    (['neither'], 'q', 'on'),
    (['no'], 'q', 'on'),
    (['no', 'more'], 'q', 'on'),
    (['part'], 'q', 'on'),
    (['some'], 'q', 'indiv'),
    (['some'], 'q', 'on'),
    (['such'], 'q', 'on'),
    (['such', 'a'], 'q', 'on'),
    (['that'], 'q', 'dem'),
    (['the'], 'q', 'on'),
    (['the', 'most'], 'q', 'on'),
    (['these'], 'q', 'dem'),
    (['this'], 'q', 'dem'),
    (['those'], 'q', 'dem'),
    (['twice'], 'q', 'on'),
    (['umpteen'], 'q', 'on'),
    (['what', 'a'], 'q', 'on'),
    (['which'], 'q', 'on')];

  WRD_Cs = basic.Word.WRD_Cs + [
    (['after'], 'c', 'on'),
    (['after'], 'x', 'h'),
    (['albeit'], 'x', 'on'),
    (['all', 'the', 'while'], 'x', 'on'),
    (['although'], 'x', 'on'),
    (['and', 'neither'], 'x', 'subord'),
    (['and', 'so'], 'x', 'subord'),
    (['as'], 'p', 'comp'),
    (['as'], 'x', 'prd'),
    (['as'], 'x', 'subord'),
    (['as', 'far', 'as'], 'x', 'on'),
    (['as', 'if'], 'x', 'on'),
    (['as', 'in'], 'x', 'on'),
    (['as', 'long', 'as'], 'x', 'on'),
    (['as', 'though'], 'x', 'on'),
    (['because'], 'x', 'on'),
    (['before'], 'x', 'h'),
    (['but', 'neither'], 'x', 'subord'),
    (['but', 'so'], 'x', 'subord'),
    (['colon'], 'p', 'namely'),
    (['e', 'g'], 'p', 'on'),
    (['even', 'if'], 'x', 'on'),
    (['even', 'though'], 'x', 'on'),
    (['even', 'when'], 'x', 'on'),
    (['ever', 'since'], 'x', 'subord'),
    (['except'], 'p', 'on'),
    (['except'], 'x', 'h'),
    (['except', 'to'], 'x', 'on'),
    (['for'], 'p', 'on'),
    (['for'], 'x', 'cause'),
    (['for'], 'x', 'cond'),
    (['from'], 'p', 'on'),
    (['how', 'about'], 'x', 'on'),
    (['how', 'long'], 'x', 'on'),
    (['i', 'e'], 'p', 'on'),
    (['if'], 'x', 'then'),
    (['if', 'and', 'when'], 'x', 'on'),
    (['if', 'only'], 'x', 'on'),
    (['in'], 'p', 'on'),
    (['in', 'case'], 'x', 'on'),
    (['in', 'order', 'to'], 'x', 'on'),
    (['in', 'so', 'far', 'as'], 'x', 'on'),
    (['in', 'that'], 'x', 'on'),
    (['in', 'the', 'event'], 'x', 'on'),
    (['inasmuch', 'as'], 'x', 'subord'),
    (['lest'], 'x', 'on'),
    (['like'], 'x', 'preph'),
    (['namely'], 'p', 'on'),
    (['not', 'that'], 'x', 'on'),
    (['notwithstanding'], 'p', 'on'),
    (['now', 'that'], 'x', 'on'),
    (['of'], 'x', 'subord'),
    (['on'], 'p', 'on'),
    (['once'], 'x', 'subord'),
    (['other', 'than'], 'p', 'on'),
    (['over'], 'p', 'on'),
    (['provided'], 'x', 'on'),
    (['providing'], 'x', 'on'),
    (['rather', 'than'], 'p', 'on'),
    (['since'], 'x', 'subord'),
    (['so', 'as', 'to'], 'x', 'on'),
    (['so', 'long', 'as'], 'x', 'on'),
    (['so', 'much', 'so', 'that'], 'x', 'on'),
    (['so', 'that'], 'x', 'on'),
    (['such', 'as'], 'p', 'on'),
    (['such', 'as'], 'x', 'h'),
    (['such', 'that'], 'x', 'on'),
    (['therefore'], 'x', 'on'),
    (['though'], 'x', 'on'),
    (['unless'], 'x', 'on'),
    (['until'], 'p', 'on'),
    (['until'], 'x', 'h'),
    (['up', 'until'], 'p', 'on'),
    (['viz'], 'p', 'on'),
    (['what', 'of'], 'x', 'on'),
    (['when'], 'x', 'subord'),
    (['whence'], 'p', 'on'),
    (['whenever'], 'x', 'subord'),
    (['where'], 'x', 'subord'),
    (['whereas'], 'x', 'on'),
    (['whereby'], 'x', 'on'),
    (['wherever'], 'x', 'subord'),
    (['whether'], 'x', 'on'),
    (['whether', 'or', 'not'], 'x', 'on'),
    (['while'], 'x', 'on'),
    (['whilst'], 'x', 'on'),
    (['whither'], 'p', 'on'),
    (['why'], 'x', 'on'),
    (['why', 'not'], 'x', 'on'),
    (['with'], 'x', 'subord')];

  WRD_Ms = basic.Word.WRD_Ms + [
    (['a', 'bit'], 'x', 'deg'),
    (['a', 'full'], 'x', 'deg'),
    (['a', 'good', 'deal'], 'x', 'on'),
    (['a', 'half'], 'x', 'on'),
    (['a', 'little'], 'x', 'deg'),
    (['a', 'little', 'bit'], 'x', 'on'),
    (['a', 'lot'], 'x', 'on'),
    (['a', 'tad'], 'x', 'deg'),
    (['a', 'ways'], 'x', 'much'),
    (['about'], 'x', 'deg'),
    (['absolutely'], 'x', 'deg'),
    (['after'], 'x', 'h'),
    (['albeit'], 'x', 'on'),
    (['all'], 'x', 'deg'),
    (['all', 'that'], 'x', 'deg'),
    (['all', 'the', 'more'], 'x', 'on'),
    (['all', 'the', 'way'], 'x', 'deg'),
    (['all', 'the', 'while'], 'x', 'on'),
    (['almost'], 'x', 'deg'),
    (['already'], 'x', 'deg'),
    (['although'], 'x', 'on'),
    (['altogether'], 'x', 'on'),
    (['always'], 'x', 'deg'),
    (['and'], 'c', 'on'),
    (['and', 'neither'], 'x', 'subord'),
    (['and', 'so'], 'x', 'subord'),
    (['any'], 'x', 'deg'),
    (['approx'], 'x', 'on'),
    (['approximately'], 'x', 'deg'),
    (['approximately'], 'x', 'on'),
    (['around'], 'x', 'deg'),
    (['as'], 'x', 'prd'),
    (['as'], 'x', 'subord'),
    (['as', 'far', 'as'], 'x', 'on'),
    (['as', 'if'], 'x', 'on'),
    (['as', 'in'], 'x', 'on'),
    (['as', 'long', 'as'], 'x', 'on'),
    (['as', 'though'], 'x', 'on'),
    (['at', 'least'], 'x', 'deg'),
    (['at', 'most'], 'x', 'deg'),
    (['at', 'the', 'most'], 'x', 'deg'),
    (['at', 'worst'], 'x', 'on'),
    (['awful'], 'x', 'deg'),
    (['awfully'], 'x', 'on'),
    (['back'], 'x', 'deg'),
    (['barely'], 'x', 'deg'),
    (['basic'], 'x', 'on'),
    (['basically'], 'x', 'deg'),
    (['because'], 'x', 'on'),
    (['before'], 'x', 'h'),
    (['better'], 'x', 'deg'),
    (['bitterly'], 'x', 'deg'),
    (['borderline'], 'x', 'deg'),
    (['but'], 'c', 'on'),
    (['but', 'neither'], 'x', 'subord'),
    (['but', 'so'], 'x', 'subord'),
    (['chiefly'], 'x', 'deg'),
    (['clear'], 'x', 'deg'),
    (['comparably'], 'x', 'deg'),
    (['completely'], 'x', 'deg'),
    (['consequently'], 'x', 'deg'),
    (['damn'], 'x', 'deg'),
    (['damned'], 'x', 'deg'),
    (['darned'], 'x', 'deg'),
    (['deep'], 'x', 'deg'),
    (['directly'], 'x', 'deg'),
    (['distressingly'], 'x', 'deg'),
    (['downright'], 'x', 'deg'),
    (['dreadfully'], 'x', 'deg'),
    (['drop-dead'], 'x', 'deg'),
    (['due'], 'x', 'dir'),
    (['effing'], 'x', 'deg'),
    (['eminently'], 'x', 'deg'),
    (['entirely'], 'x', 'on'),
    (['especially'], 'x', 'deg'),
    (['essentially'], 'x', 'deg'),
    (['even'], 'x', 'deg'),
    (['even', 'if'], 'x', 'on'),
    (['even', 'though'], 'x', 'on'),
    (['even', 'when'], 'x', 'on'),
    (['ever', 'since'], 'x', 'subord'),
    (['every'], 'x', 'deg'),
    (['every', 'bit'], 'x', 'deg'),
    (['exactly'], 'x', 'deg'),
    (['except'], 'x', 'h'),
    (['except', 'to'], 'x', 'on'),
    (['extra'], 'x', 'on'),
    (['extremely'], 'x', 'deg'),
    (['fairly'], 'x', 'on'),
    (['far'], 'x', 'deg'),
    (['far', 'from'], 'x', 'deg'),
    (['farther'], 'x', 'deg'),
    (['fewer', 'than'], 'x', 'on'),
    (['first', 'and', 'foremost'], 'x', 'deg'),
    (['for'], 'x', 'cause'),
    (['for'], 'x', 'cond'),
    (['fucking'], 'x', 'deg'),
    (['fully'], 'x', 'deg'),
    (['further'], 'x', 'deg'),
    (['generally'], 'x', 'on'),
    (['halfway'], 'x', 'on'),
    (['hardly'], 'x', 'deg'),
    (['high'], 'x', 'deg'),
    (['higher'], 'x', 'deg'),
    (['hitherto'], 'x', 'deg'),
    (['how', 'about'], 'x', 'on'),
    (['how', 'long'], 'x', 'on'),
    (['if'], 'x', 'then'),
    (['if', 'and', 'when'], 'x', 'on'),
    (['if', 'only'], 'x', 'on'),
    (['immediately'], 'x', 'deg'),
    (['impossibly'], 'x', 'on'),
    (['in', 'case'], 'x', 'on'),
    (['in', 'excess', 'of'], 'x', 'deg'),
    (['in', 'order', 'to'], 'x', 'on'),
    (['in', 'so', 'far', 'as'], 'x', 'on'),
    (['in', 'that'], 'x', 'on'),
    (['in', 'the', 'event'], 'x', 'on'),
    (['inasmuch', 'as'], 'x', 'subord'),
    (['increasingly'], 'x', 'deg'),
    (['incredibly'], 'x', 'deg'),
    (['intensely'], 'x', 'on'),
    (['jam'], 'x', 'deg'),
    (['just'], 'x', 'deg'),
    (['just', 'about'], 'x', 'deg'),
    (['kind', 'of'], 'x', 'deg'),
    (['largely'], 'x', 'on'),
    (['least'], 'x', 'deg'),
    (['less', 'than'], 'x', 'on'),
    (['lest'], 'x', 'on'),
    (['like'], 'x', 'preph'),
    (['little'], 'x', 'deg'),
    (['low'], 'x', 'deg'),
    (['lower'], 'x', 'deg'),
    (['mainly'], 'x', 'deg'),
    (['max'], 'x', 'deg'),
    (['maybe'], 'x', 'deg'),
    (['merely'], 'x', 'deg'),
    (['midway'], 'x', 'on'),
    (['mighty'], 'x', 'deg'),
    (['more', 'than'], 'x', 'on'),
    (['mostly'], 'x', 'deg'),
    (['much'], 'x', 'deg'),
    (['near'], 'x', 'deg'),
    (['nearly'], 'x', 'deg'),
    (['next'], 'x', 'deg'),
    (['no'], 'x', 'deg'),
    (['no', 'less', 'than'], 'x', 'on'),
    (['no', 'more', 'than'], 'x', 'on'),
    (['normally'], 'x', 'deg'),
    (['not'], 'x', 'deg'),
    (['not', 'even'], 'x', 'deg'),
    (['not', 'just'], 'x', 'deg'),
    (['not', 'least'], 'x', 'deg'),
    (['not', 'more', 'than'], 'x', 'on'),
    (['not', 'only'], 'x', 'deg'),
    (['not', 'quite'], 'x', 'on'),
    (['not', 'that'], 'x', 'on'),
    (['not', 'the', 'least'], 'x', 'deg'),
    (['now', 'that'], 'x', 'on'),
    (['of'], 'x', 'subord'),
    (['once'], 'x', 'deg'),
    (['once'], 'x', 'subord'),
    (['only'], 'x', 'deg'),
    (['or'], 'c', 'on'),
    (['outright'], 'x', 'deg'),
    (['over'], 'x', 'deg'),
    (['overly'], 'x', 'on'),
    (['particularly'], 'x', 'deg'),
    (['partly'], 'x', 'deg'),
    (['perfectly'], 'x', 'on'),
    (['possibly'], 'x', 'deg'),
    (['practically'], 'x', 'deg'),
    (['precisely'], 'x', 'deg'),
    (['pretty'], 'x', 'on'),
    (['pretty', 'much'], 'x', 'deg'),
    (['pretty', 'well'], 'x', 'deg'),
    (['primarily'], 'x', 'deg'),
    (['probably'], 'x', 'deg'),
    (['provided'], 'x', 'on'),
    (['providing'], 'x', 'on'),
    (['quite'], 'x', 'on'),
    (['rather'], 'x', 'on'),
    (['real'], 'x', 'deg'),
    (['reasonably'], 'x', 'deg'),
    (['regularly'], 'x', 'on'),
    (['relatively'], 'x', 'deg'),
    (['remotely'], 'x', 'deg'),
    (['ridiculously'], 'x', 'on'),
    (['right'], 'x', 'deg'),
    (['rough'], 'x', 'deg'),
    (['shortly'], 'x', 'deg'),
    (['significantly'], 'x', 'on'),
    (['simply'], 'x', 'deg'),
    (['since'], 'x', 'subord'),
    (['smack'], 'x', 'deg'),
    (['so', 'as', 'to'], 'x', 'on'),
    (['so', 'long', 'as'], 'x', 'on'),
    (['so', 'much', 'so', 'that'], 'x', 'on'),
    (['so', 'that'], 'x', 'on'),
    (['somewhat'], 'x', 'deg'),
    (['sort', 'of'], 'x', 'deg'),
    (['steeply'], 'x', 'deg'),
    (['still'], 'x', 'deg'),
    (['straight'], 'x', 'deg'),
    (['such', 'as'], 'x', 'h'),
    (['such', 'that'], 'x', 'on'),
    (['sufficiently'], 'x', 'deg'),
    (['super'], 'x', 'deg'),
    (['terribly'], 'x', 'deg'),
    (['that'], 'x', 'deg'),
    (['therefore'], 'x', 'on'),
    (['this'], 'x', 'deg'),
    (['though'], 'x', 'on'),
    (['twice'], 'x', 'deg'),
    (['uh'], 'x', 'on'),
    (['unbelievably'], 'x', 'deg'),
    (['under'], 'x', 'deg'),
    (['unless'], 'x', 'on'),
    (['until'], 'x', 'h'),
    (['unusually'], 'x', 'deg'),
    (['up', 'to'], 'x', 'deg'),
    (['very'], 'x', 'deg'),
    (['very', 'much'], 'x', 'deg'),
    (['virtually'], 'x', 'deg'),
    (['vitally'], 'x', 'on'),
    (['way'], 'x', 'deg'),
    (['way', 'too'], 'x', 'deg'),
    (['well'], 'x', 'deg'),
    (['what', 'of'], 'x', 'on'),
    (['when'], 'x', 'subord'),
    (['whenever'], 'x', 'subord'),
    (['where'], 'x', 'subord'),
    (['whereas'], 'x', 'on'),
    (['whereby'], 'x', 'on'),
    (['wherever'], 'x', 'subord'),
    (['whether'], 'x', 'on'),
    (['whether', 'or', 'not'], 'x', 'on'),
    (['while'], 'x', 'on'),
    (['whilst'], 'x', 'on'),
    (['wholly'], 'x', 'deg'),
    (['why'], 'x', 'on'),
    (['why', 'not'], 'x', 'on'),
    (['wide'], 'x', 'deg'),
    (['with'], 'x', 'subord'),
    (['wonderfully'], 'x', 'deg'),
    (['yet'], 'x', 'deg')];

  WRD_Ps = basic.Word.WRD_Ps + [
    (['albeit'], 'c', 'on'),
    (['and'], 'c', 'on'),
    (['and', 'also'], 'c', 'on'),
    (['and', 'finally'], 'c', 'on'),
    (['and', 'not'], 'c', 'on'),
    (['and', 'so'], 'c', 'on'),
    (['and', 'then'], 'c', 'on'),
    (['and', 'thus'], 'c', 'on'),
    (['and', 'yet'], 'c', 'on'),
    (['as', 'well', 'as'], 'c', 'on'),
    (['but'], 'c', 'on'),
    (['but', 'also'], 'c', 'on'),
    (['but', 'not'], 'c', 'on'),
    (['but', 'then'], 'c', 'on'),
    (['et', 'al'], 'c', 'on'),
    (['etc'], 'c', 'on'),
    (['even'], 'c', 'on'),
    (['except'], 'c', 'on'),
    (['except', 'that'], 'c', 'on'),
    (['if', 'not'], 'c', 'on'),
    (['instead', 'of'], 'c', 'on'),
    (['let', 'alone'], 'c', 'on'),
    (['minus'], 'c', 'on'),
    (['much', 'less'], 'c', 'on'),
    (['nor'], 'c', 'on'),
    (['not'], 'c', 'on'),
    (['not', 'to', 'mention'], 'c', 'on'),
    (['or'], 'c', 'on'),
    (['or', 'else'], 'c', 'on'),
    (['plus'], 'c', 'on'),
    (['plus-minus'], 'c', 'on'),
    (['rather', 'than'], 'c', 'on'),
    (['so'], 'c', 'on'),
    (['so', 'on'], 'c', 'on'),
    (['then'], 'c', 'on'),
    (['to', 'name', 'a', 'few'], 'c', 'on'),
    (['versus'], 'c', 'on'),
    (['vice', 'versa'], 'c', 'on'),
    (['yet'], 'c', 'on')];

